version: "3"

services:
  mongo:
    image: mongo:4.4.4
    container_name: host.docker.internal
    restart: always
    networks:
      - app-network
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge
