version: "3"

services:
  mongo.cipay:
    image: mongo:4.4.4
    container_name: mongo.cipay
    restart: always
    networks:
      - app-network
    volumes:
      - ./data/db:/data/db
    ports:
      - "${DB_PORT}:${DB_PORT}"  


networks:
  app-network:
    driver: bridge
