version: "3"

services:
  mongo.cipay:
    image: mongo:4.4.4
    container_name: mongo.cipay-${CHAIN_ID}
    restart: always
    networks:
      - app-network
    volumes:
      - ./data/db-${CHAIN_ID}:/data/db-${CHAIN_ID}
    ports:
      - "${DB_PORT}:${DB_PORT}"  


networks:
  app-network:
    driver: bridge
